#!/bin/bash

mkdir -p bin

source common

find src-instr -name *.java | xargs javac -cp $CLASSPATH -d bin
find src -name *.java | xargs javac -g -cp $CLASSPATH -d bin
find src-examples -name *.java | xargs javac -g -cp $CLASSPATH -d bin
NUM=`find bin -name *class | wc -l`
echo "compiled $NUM classes"
cp `find dat -name "*.txt" | xargs` bin
cp `find dat -name "*.xml" | xargs` bin
cp `find dat -name "*.properties" | xargs` bin
