#!/bin/bash

mkdir -p bin

find src -name *.java | xargs javac -g -cp libs/wala-r3501-slice.jar -d bin
NUM=`find bin -name *class | wc -l`
echo "compiled $NUM classes"
cp `find dat -name "*.txt" | xargs` bin
cp `find dat -name "*.xml" | xargs` bin
cp `find dat -name "*.properties" | xargs` bin

######################  generate jar file for application
(cd bin;
    find examples -name "*.class" | xargs jar cvf examples.jar
    mv examples.jar ..
)