#!/bin/bash

CURRDIR=`pwd`
BINDIR=${CURRDIR}/bin
LIBDIR=${CURRDIR}/libs

CLASSPATH=$BINDIR
for x in `ls $LIBDIR/*.jar`
do
    CLASSPATH=$CLASSPATH:$x
done

OS_KERNEL=`uname -s`
if [ $OS_KERNEL = "Darwin" ]
    then
        DOTPATH="/usr/local/bin/dot"
    else
        DOTPATH="/usr/bin/dot"
fi