#!/bin/bash

## takes parameter if one is passed
## otherwise, uses "examples" as 
## default name
if [ -z "$1" ];
then
    NAME="examples"
else
    NAME="$1"
fi

case "$NAME" in
    "101" ) 
	PREFIX="companies101/org/softlang"
	;;
    * ) 
	PREFIX="examples"
	;;
esac

######################  generate jar file for application
(cd bin;
    find "${PREFIX}" -name "*.class" | xargs jar cvf $NAME.jar
    mv $NAME.jar ..
)