#!/bin/bash

case "$1" in
    "101" ) 
	PREFIX="companies101/org/softlang"
	NAME="$1"
	;;
    "coffee" ) 
	PREFIX="coffeemaker"
	NAME="$1"
	;;
    "foo" ) 
	PREFIX="foo"
	NAME="foo"
	;;
    * ) 
	echo "please inform the name of the subject "
	exit;
esac

######################  generate jar file for application
(cd bin;
    find "${PREFIX}" -name "*.class" | xargs jar cvf $NAME.jar
    mv $NAME.jar ..
)