#!/bin/bash

source common

## takes parameter if one is passed
## otherwise, uses "examples" as 
## default name
if [ -z "$1" ];
then
    NAME="examples"
else
    NAME="$1"
fi

## complete this as you add new examples
case "$NAME" in
    "101" ) 
	JARFILE="101.jar"
	PREFIX="org/softlang"
	;;
    * ) 
	JARFILE="examples.jar"
	PREFIX="examples"
	;;
esac

## call java depend.Main
java -cp ".:bin:libs/wala-r3501-slice.jar" \
    depend.Main \
    -appJar=${JARFILE} \
    -printWalaWarnings=false \
    -exclusionFile=ExclusionAllJava.txt \
    -exclusionFileForCallGraph=ExclusionForCallGraph.txt \
    -dotPath=${DOTPATH} \
    -appPrefix=${PREFIX} \
    -listAppClasses=false \
    -listAllClasses=false \
    -listAppMethods=false \
    -genCallGraph=false \
    -measureTime=false \
    -targetLine="22" \
    -targetClass="Lexamples/B" \
    -targetMethod="n_(Lexamples/A;Lexamples/C;)V" \
    -reportType=dot ## [list, dot]