#!/bin/bash

source common

## takes parameter if one is passed
## otherwise, uses "examples" as 
## default name
if [ -z "$1" ];
then
    NAME="examples"
else
    NAME="$1"
fi

## complete this as you add new examples
case "$NAME" in
    "101" ) 
	### 101 project
	JARFILE="101.jar"
	PREFIX="companies101/org/softlang"
	LINE="37"
	CLASS="Lcompanies101/org/softlang/swing/model/Model"
	METHOD="getTotal()Ljava/lang/String;"
	;;
    "coffee" ) 
	### 101 project
	JARFILE="coffee.jar"
	PREFIX="coffee"
	LINE="99"
	CLASS="Lcoffeemaker/CoffeeMaker"
	METHOD="editRecipe(Lcoffeemaker/Recipe;Lcoffeemaker/Recipe;)Z"
	;;
    * ) 
	### default
	JARFILE="examples.jar"
	PREFIX="foo"
	LINE="22"
	CLASS="Lfoo/B"
	METHOD="n_(Lfoo/A;Lfoo/C;)V"
	;;
esac

## call java depend.Main
java -cp ".:bin:libs/wala-r3501-slice.jar" \
    depend.Main \
    -appJar=${JARFILE} \
    -printWalaWarnings=false \
    -exclusionFile=ExclusionAllJava.txt \
    -exclusionFileForCallGraph=ExclusionForCallGraph.txt \
    -dotPath=${DOTPATH} \
    -appPrefix=${PREFIX} \
    -listAppClasses=false \
    -listAllClasses=false \
    -listAppMethods=false \
    -genCallGraph=false \
    -measureTime=false \
    -targetLine=${LINE} \
    -targetClass=${CLASS} \
    -targetMethod=${METHOD} \
    -reportType=dot ## [list, dot]